format = """
[░▒▓](black)\
$username\
[](bg:blue fg:black)\
$directory\
[](fg:blue bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#2b3248)\
$nodejs\
$rust\
$python\
$golang\
[](fg:#2b3248 bg:#1d2230)\
$conda\
[](fg:#1d2230)\
\n$character"""

# add_newline = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](blue)"

[username]
show_always = true
style_user = "bg:black fg:white"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "fg:black bg:blue"
format = "[ $path ]($style)"
truncation_length = 100
truncation_symbol = "…/"
truncate_to_repo = false

[conda]
format = '[  $environment ](fg:green bg:#1d2230)'
ignore_base = false

#[directory.substitutions]
#"Documents" = "󰈙"
#"Downloads" = ""
#"Music" = ""
#"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:white bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:white bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#2b3248"
format = '[[ $symbol ($version) ](fg:white bg:#2b3248)]($style)'

[python]
symbol = ""
style = "bg:#2b3248"
format = '[[ $symbol ($version) ](fg:white bg:#2b3248)]($style)'

[rust]
symbol = ""
style = "bg:#2b3248"
format = '[[ $symbol ($version) ](fg:white bg:#2b3248)]($style)'

[golang]
symbol = ""
style = "bg:#2b3248"
format = '[[ $symbol ($version) ](fg:white bg:2b3248)]($style)'

#[time]
#disabled = true
#time_format = "%R" # Hour:Minute Format
#style = "bg:#1d2230"
#format = '[[ $time](fg:#a0a9cb bg:#1d2230)]($style)'
